name: Build
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  linux:
    strategy:
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Restore cache
      id: restore-cache-action
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ matrix.arch }}-buildx
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        file: ${{ github.workspace }}/docker/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        tags: vanilla_build:latest
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        platforms: ${{ matrix.arch }}
    
    - name: Save cache
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ steps.restore-cache-action.outputs.cache-primary-key }}
    
    - name: Run Docker container
      run: docker run --platform ${{ matrix.arch }} -v "$GITHUB_WORKSPACE:/vanilla" vanilla_build:latest
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path:
          ${{ github.workspace }}/Vanilla_U-${{ matrix.arch }}.AppImage

      
