name: Build
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  linux:
    strategy:
      matrix:
        arch: [ x86_64, aarch64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt -y install qemu-user-static
    
    - name: Run Docker container
      run: docker run --platform ${{ matrix.arch }} -v "$GITHUB_WORKSPACE:/vanilla" itsmattkc/vanilla-u-build:${{ matrix.arch }}-latest
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vanilla U (${{ matrix.arch }})
        path: ${{ github.workspace }}/Vanilla_U-${{ matrix.arch }}.tar.gz

      
